name: twiliochat
description: A Flutter plugin for Twilio https://www.twilio.com/chat for Android and iOS
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: co.quetool.twiliochat
        pluginClass: TwiliochatPlugin
      ios:
        pluginClass: TwiliochatPlugin
